### ISSUE TITLE
Missing raw_process.ipynb file

### ISSUE THREAD

**Issue by vandyxiaowei** [PeterGriffinJin/Graph-CoT#1]
Hi, @PeterGriffinJin 

Thanks a lot for the awesome work! We find your paper very interesting and the benchmark is really valuable to the community. 

I am trying to run your benchmark following README. I downloaded the raw data, but cannot find raw_process.ipynb file as instructed. Would you mind sharing this file or sometime in future? 

Thanks!

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you so much for your interest!

We have uploaded the raw_process.ipynb for each domain and modify the readme in https://github.com/PeterGriffinJin/Graph-CoT/tree/main/data.

If you want to run models on GRBench directly, you can refer to the instruction here (no need to run raw_process.ipynb):
<img width="1010" alt="image" src="https://github.com/PeterGriffinJin/Graph-CoT/assets/48234654/5c6bda68-29a0-4516-9635-89dc8a75ba03">

If you are interested in how GRBench is constructed, you can go through the following sections.

Please feel free to let me know if you have any other questions!

Best,
Bowen

**Comment by vandyxiaowei** [comment]
Thank you Bowen for uploading the processed graph data and the scripts!

**Comment by vandyxiaowei** [comment]
An additional suggestion is maybe it is more convenient to also provide the reference solution paths for each question-answer pair, although it can be generated from the notebook with the processed graph files (which is huge). Thanks!
