### ISSUE TITLE
Ground truths sourcing questions.

### ISSUE THREAD

**Issue by HouyuZhang1007** [PeterGriffinJin/Graph-CoT#3]
Hi thanks for releasing the code and the benchmark. 

A question related to the paper: in section 3.5 you mentioned that the ground truth answers are generated by graph functions (e.g. neighbor check, degree check) followed by function chains. In your proposed framework Graph Chain-of-Thought looks like the same/similar NeighborCheck(NodeID, NeighborType) and NodeDegree(NodeID, NeighborType) are used.

If the implementation between the way you gather ground truths and your proposed model shares overlaps, would that cause bias for the benchmark to favor your models?

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you so much for your comments and your interest in our work.

The goal of constructing GRBench is to provide a dataset to **simulate the real-world needs of retrieving, reading, and reasoning on external informative text-attributed graphs** (just like how humans navigate the web: search/read the pages/thinking or click on some hyperlinks). To achieve this goal, we manually write question templates (section 3.5) to develop data samples automatically. All the codes can be found at https://github.com/PeterGriffinJin/Graph-CoT/tree/main/data/processed_data. **This part's implementation does not overlap with the implementation of Graph CoT.**



Although these tasks seem trivial to humans, they are extremely hard for LLMs. The proposed Graph CoT is designed to let LLM have the ability to navigate the graphs. However, Graph CoT is not perfect, given that the LLMs sometimes fail to understand the graph and it's challenging to let LLMs conduct complex reasoning. This leaves room for future study.

Best,
Bowen
