### ISSUE TITLE
Cost of api

### ISSUE THREAD

**Issue by sjd12138** [PeterGriffinJin/Graph-CoT#4]
Hi, thanks for releasing the code and the benchmark.

A question related to the project: considering that the API calls are charged based on the number of tokens used, how can we estimate the cost of running the project with a specific dataset? For example, if we have a dataset of 6.7GB, how can we calculate the expected cost for both input and output tokens, and are there any cost-saving strategies you would recommend, such as using batch API pricing or optimizing token usage? Additionally, how do you handle large datasets in terms of tokenization and cost efficiency in your implementation?

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you for your message.

The cost of running Graph-CoT on a specific dataset can be estimated by thinking about how many reasoning steps your queries need and how many tokens each reasoning/graph execution will take up. It is not directly related to the size of the graph data.

One way to save the token cost implemented in our Graph-CoT is to make detailed graph function execution. For example, when we fetch the neighbors of a node, we can avoid returning the whole neighbor set including all types of neighbors but only return the neighbors whose type we are interested in. The same is also to node features.

Best,
Bowen
