### ISSUE TITLE
where is the item_dedup.csv?

### ISSUE THREAD

**Issue by nxlogn** [PeterGriffinJin/Graph-CoT#5]
![image](https://github.com/user-attachments/assets/e051c4bf-eef8-4501-8871-10053fec189a)
can not find it with your links, should i get it on some website?
![image](https://github.com/user-attachments/assets/14014e5d-dc79-479f-89be-709f637979ed)

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you for reaching out!

Those data should be about to be downloaded here:
http://snap.stanford.edu/data/amazon/productGraph/user_dedup.json.gz
http://snap.stanford.edu/data/amazon/productGraph/item_dedup.json.gz

Feel free to let me know if you have any other questions.

Best,
Bowen
