### ISSUE TITLE
Running Legal dataset

### ISSUE THREAD

**Issue by amayuelas** [PeterGriffinJin/Graph-CoT#7]
I'm trying to reproduce the results for the Legal dataset. 
But it seems I'm unable to load it in a server with 400GB RAM. 
Is there something I am missing? Are we supposed to do something else for this dataset? How many GBs did your machine have?

**Comment by PeterGriffinJin** [comment]
Hi there,

Thank you for reaching out!

The Legal graph is the biggest one. We run the experiment on the legal graph with a 1008GB RAM server.

You can try on other graphs which are much smaller than the legal graph.

Best,
Bowen
