### ISSUE TITLE
Version conflict between nvidia faiss-gpu and python3.8

### ISSUE THREAD

**Issue by YiboZhao624** [PeterGriffinJin/Graph-CoT#8]
Thank you for your excellent work! However, when I attempted to install `nvidia faiss-gpu` using the command `conda install -c pytorch -c nvidia faiss-gpu=1.7.4,` I encountered the following error:
`faiss-gpu 1.7.4 requires Python 3.8.*, which conflicts with any previously installable versions.`

It seems there might be an issue with the version. I would appreciate it if you could check and resolve this.

**Comment by PeterGriffinJin** [comment]
Hi Yibo,

Thank you for the message.

The issue is because of the misalignment between your Python version and the faiss-gpu version. You can create a new conda environment with python >= 3.8 installed with the following command (you may need to install miniconda first https://docs.anaconda.com/miniconda/install/#quick-command-line-install):

```
conda create --name graphcot python==3.8
conda activate graphcot
```

Then run the command:

```
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
conda install -c pytorch -c nvidia faiss-gpu=1.7.4
pip3 install -r requirements.txt
```

Best,
Bowen

**Comment by YiboZhao624** [comment]
> Hi Yibo,
> 
> Thank you for the message.
> 
> The issue is because of the misalignment between your Python version and the faiss-gpu version. You can create a new conda environment with python >= 3.8 installed with the following command (you may need to install miniconda first https://docs.anaconda.com/miniconda/install/#quick-command-line-install):
> 
> ```
> conda create --name graphcot python==3.8
> conda activate graphcot
> ```
> 
> Then run the command:
> 
> ```
> conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
> conda install -c pytorch -c nvidia faiss-gpu=1.7.4
> pip3 install -r requirements.txt
> ```
> 
> Best, Bowen

I'm sorry, I made a mistake earlier because I didn't check the GPT's response carefully. The actual error message is as follows:
```
Could not solve for environment specs
The following packages are incompatible
├─ cudatoolkit 11.3**  is requested and can be installed;
├─ faiss-gpu 1.7.4**  is installable with the potential options
│  ├─ faiss-gpu 1.7.4 would require
│  │  └─ libfaiss 1.7.4 h13c3c6d_0_cuda11.4, which requires
│  │     └─ cudatoolkit >=11.4.1,<11.5.0a0 , which conflicts with any installable versions previously reported;
│  ├─ faiss-gpu 1.7.4 would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  └─ faiss-gpu 1.7.4 would require
│     └─ python >=3.9,<3.10.0a0 , which can be installed;
└─ pin-1 is not installable because it requires
   └─ python 3.8.* , which conflicts with any installable versions previously reported.
```
the given script in README installs the cudatoolkit 11.3 and python 3.8, but they are not suitable for the faiss-gpu 1.7.4.

**Comment by YiboZhao624** [comment]
I tried to install python 3.9 and cudatoolkit 11.4.1 to fit the faiss 1.7.4, but the torchaudio meets the confliction. Then I installed Python 3.8, cudatoolkit 11.3 as README, and Faiss-Gpu 1.7.3. There is no version conflict anymore and it solves this problem. I will pull a PR soon the fix the readme.
